# Generated by Django 4.0 on 2021-12-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('post', models.CharField(max_length=50, null=True)),
                ('detail', models.TextField(null=True)),
                ('image', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Blog_category',
        ),
    ]
