# Generated by Django 4.0 on 2021-12-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaap', '0003_book_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='')),
                ('name', models.CharField(max_length=50, null=True)),
                ('detail', models.CharField(max_length=500, null=True)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
    ]
