# Generated by Django 4.0 on 2021-12-21 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaap', '0004_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
