# Generated by Django 4.0 on 2021-12-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaap', '0006_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_choice',
            field=models.CharField(choices=[('cakes', 'cakes'), ('chinese', 'chinese'), ('indian', 'indian'), ('italian', 'italian')], max_length=30),
        ),
    ]
