# Generated by Django 4.0 on 2021-12-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaap', '0007_alter_menu_menu_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='detail',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
